In [ ]:
'''
groupby
rename
sort values
agg functions -> sum, mean, count, min, max, nunique (count of unique values)
map
to_markdown
agg
'''

In [27]:
import pandas as pd

In [28]:
df = pd.read_csv('cleaned_hr.csv')
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,Hire_Month_Name,Hire_Day_Name,Salary_Label,sal_id,Salary_Label_id,Sal_First,Sal_Last,First_Name,Middle_Name,Last_Name
0,Bacong Alejandro,10250,0,2,1,1,3,3,0,50178,...,January,Monday,Low Salary,0,0,Low,Salary,Alejandro,NaN,Bacong
1,Baczenski Rachael,10252,1,1,0,5,5,3,1,54670,...,January,Monday,Low Salary,0,0,Low,Salary,Rachael,NaN,Baczenski
2,Barbara Thomas,10242,1,1,1,5,5,3,1,47211,...,April,Monday,Low Salary,0,0,Low,Salary,Thomas,NaN,Barbara
3,Barbossa Hector,10012,0,2,1,1,3,4,1,92328,...,November,Monday,Average Salary,1,1,Average,Salary,Hector,NaN,Barbossa
4,Barone Francesco A,10265,0,0,1,1,5,3,0,58709,...,February,Monday,Low Salary,0,0,Low,Salary,Francesco,A,Barone

In [29]:
# Find total employees by each department.
dep_emp = df.groupby('Department')['EmpID'].count()
# dep_emp

In [30]:
dep_emp = df.groupby('Department')['EmpID'].count().reset_index().rename(
    columns = {'EmpID': 'Total Employees', 'Department': 'Departments'}
).sort_values(ascending=False, by='Total Employees', ignore_index=True)
dep_emp

            Departments  Total Employees
0            Production              209
1                 IT/IS               50
2                 Sales               31
3  Software Engineering               11
4         Admin Offices                9
5      Executive Office                1

In [31]:
dep_emp = df.groupby('Department')['EmpID'].count().rename_axis('Departments').rename(
    'Total Employees'
).sort_values(ascending=False).to_markdown(stralign='center', numalign='center')
print(dep_emp)

|     Departments      |  Total Employees  |
|:--------------------:|:-----------------:|
|      Production      |        209        |
|        IT/IS         |        50         |
|        Sales         |        31         |
| Software Engineering |        11         |
|    Admin Offices     |         9         |
|   Executive Office   |         1         |

In [32]:
def currencyConverter(dataframe:str, prefix:str, *args:str):
    for col in args:
        dataframe[col] = dataframe[col].map(f'{prefix}''{:,.2f}'.format)

In [34]:
## Find total employees, total and average salary distributed to employees in each department.
emp_details = df.groupby('Department').agg(
    Total_Employees = ('EmpID', 'count'),
    Total_Salary = ('Salary', 'sum'),
    Average_Salary = ('Salary', 'mean')
).reset_index()
emp_details.columns = emp_details.columns.str.replace('_', ' ', regex=False)
currencyConverter(emp_details, '$', 'Total Salary', 'Average Salary')
# emp_details['Total Salary'] = emp_details['Total Salary'].map('${:,.2f}'.format)
# emp_details['Average Salary'] = emp_details['Average Salary'].map('${:,.2f}'.format)
emp_details

             Department  Total Employees    Total Salary Average Salary
0         Admin Offices                9     $646,127.00     $71,791.89
1      Executive Office                1     $250,000.00    $250,000.00
2                 IT/IS               50   $4,853,232.00     $97,064.64
3            Production              209  $12,530,291.00     $59,953.55
4                 Sales               31   $2,140,899.00     $69,061.26
5  Software Engineering               11   $1,044,884.00     $94,989.45

In [36]:
df.columns

Index(['Employee_Name', 'EmpID', 'MarriedID', 'MaritalStatusID', 'GenderID',
       'EmpStatusID', 'DeptID', 'PerfScoreID', 'FromDiversityJobFairID',
       'Salary', 'Termd', 'PositionID', 'Position', 'State', 'Zip', 'DOB',
       'Gender', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino', 'RaceDesc',
       'DateofHire', 'DateofTermination', 'TermReason', 'EmploymentStatus',
       'Department', 'ManagerName', 'ManagerID', 'RecruitmentSource',
       'PerformanceScore', 'EngagementSurvey', 'EmpSatisfaction',
       'SpecialProjectsCount', 'LastPerformanceReview_Date', 'DaysLateLast30',
       'Absences', 'Hire_Year', 'Hire_Month', 'Hire_Day', 'Hire_Month_Name',
       'Hire_Day_Name', 'Salary_Label', 'sal_id', 'Salary_Label_id',
       'Sal_First', 'Sal_Last', 'First_Name', 'Middle_Name', 'Last_Name'],
      dtype='object')

In [43]:
## Growth Pct = ((current value - baseline value) / baseline value)*100
# ((45 - 83)/83)*100

In [47]:
## Find total number of employees hired in each year.
hire_year_emp = df.groupby('Hire_Year')['EmpID'].count().reset_index().rename(
    columns = {'Hire_Year': 'Hire Year', 'EmpID': 'Total Employees'}
)
hire_year_emp['Hire%'] = (hire_year_emp['Total Employees'].pct_change().fillna(0))*100
hire_year_emp['Hire%'] = hire_year_emp['Hire%'].map('{:,.2f}%'.format)
hire_year_emp

    Hire Year  Total Employees    Hire%
0        2006                1    0.00%
1        2007                2  100.00%
2        2008                3   50.00%
3        2009                7  133.33%
4        2010                9   28.57%
5        2011               83  822.22%
6        2012               45  -45.78%
7        2013               44   -2.22%
8        2014               60   36.36%
9        2015               36  -40.00%
10       2016               14  -61.11%
11       2017                6  -57.14%
12       2018                1  -83.33%

In [61]:
## Find total number of employees hired in each month.
emp_hire_month = df.groupby(['Hire_Month', 'Hire_Month_Name'])['EmpID'].count().reset_index().rename(
    columns = {'Hire_Month': 'Hire Month', 'EmpID': 'Total Employees', 'Hire_Month_Name': 'Month Name'}
)[['Month Name', 'Total Employees']]
emp_hire_month

   Month Name  Total Employees
0     January               54
1    February               31
2       March               19
3       April               27
4         May               33
5        June                8
6        July               44
7      August               20
8   September               39
9     October                7
10   November               28
11   December                1

In [73]:
## Find total number of employees hired in each day.
# Form category
weekdays = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
df['Hire_Day_Name'] = pd.Categorical(df['Hire_Day_Name'], categories=weekdays)

emp_hire_day = df.groupby(['Hire_Day_Name'], observed=False)['EmpID'].count().reset_index()
emp_hire_day

  Hire_Day_Name  EmpID
0        Sunday      6
1        Monday    259
2       Tuesday     19
3     Wednesday      9
4      Thursday      9
5        Friday      6
6      Saturday      3

## KPI (Key Performance Indicator)

In [81]:
total_salary = df['Salary'].sum()
total_employees = df['EmpID'].count()
total_departments = df['Department'].nunique() # count of number of unique values
total_managers = df['ManagerID'].nunique()

print(f'{total_salary:,.2f}')
print(total_employees)
print(total_departments)
print(total_managers)

21,465,433.00
311
6
23