In [104]:
import pandas as pd

In [105]:
df = pd.read_csv('cleaned_hr.csv')
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,Bacong Alejandro,10250,0,2,1,1,3,3,0,50178,...,Peter Monroe,7,Indeed,Fully Meets,5.00,5,6,2019-02-18,0,16
1,Baczenski Rachael,10252,1,1,0,5,5,3,1,54670,...,David Stanley,14,Diversity Job Fair,Fully Meets,4.20,4,0,2016-01-30,0,12
2,Barbara Thomas,10242,1,1,1,5,5,3,1,47211,...,Kissy Sullivan,20,Diversity Job Fair,Fully Meets,4.20,3,0,2016-05-06,0,15
3,Barbossa Hector,10012,0,2,1,1,3,4,1,92328,...,Simon Roup,4,Diversity Job Fair,Exceeds,4.28,4,5,2019-02-25,0,9
4,Barone Francesco A,10265,0,0,1,1,5,3,0,58709,...,Kelley Spirea,18,Google Search,Fully Meets,4.60,4,0,2019-02-14,0,7

In [106]:
def convertDateTime(dataframe, *args):
    for col in args:
        dataframe[col] = pd.to_datetime(dataframe[col], format='mixed')
    print('Date converted..')

In [107]:
convertDateTime(df, 'DOB', 'DateofHire', 'DateofTermination', 'LastPerformanceReview_Date')

Date converted..

## Extract Date

In [108]:
# dt.year/month/day
df['Hire_Year'] = df['DateofHire'].dt.year
df['Hire_Month'] = df['DateofHire'].dt.month
df['Hire_Day'] = df['DateofHire'].dt.day
df['Hire_Month_Name'] = df['DateofHire'].dt.month_name()
df['Hire_Day_Name'] = df['DateofHire'].dt.day_name()

In [109]:
# df[['DateofHire', 'Hire_Year', 'Hire_Month', 'Hire_Day', 'Hire_Month_Name', 'Hire_Day_Name']]

## Convert Continuous data to Categorical data

In [110]:
df['Salary'].head()

0    50178
1    54670
2    47211
3    92328
4    58709
Name: Salary, dtype: int64

In [111]:
df['Salary'].max() # 250000
df['Salary'].min() # 45000

45046

In [112]:
def convertSalary(salary):
    if salary >= 0 and salary <= 60000:
        return 'Low Salary'
    elif salary > 60000 and salary <= 110000:
        return 'Average Salary'
    else:
        return 'High Salary'

In [113]:
df['Salar_Label'] = df['Salary'].apply(convertSalary)
df = df.rename(columns = {'Salar_Label': 'Salary_Label'})

In [114]:
# df[['Salary', 'Salary_Label']]

## Label Encoding

In [115]:
'''
- Convert categorical record to numeric record.
- Types of Encoding
    1. Label Encoder
    2. One-Hot Encoder
    3. Manual Encoding -> Dictionary mapping
'''

'\n- Convert categorical record to numeric record.\n- Types of Encoding\n    1. Label Encoder\n    2. One-Hot Encoder\n    3. Manual Encoding -> Dictionary mapping\n'

### Manual Encoding

In [116]:
df['Salary_Label'].unique()

array(['Low Salary', 'Average Salary', 'High Salary'], dtype=object)

In [117]:
sal_dict = {
    'Low Salary': 0, 
    'Average Salary': 1, 
    'High Salary': 2
}
df['sal_id'] = df['Salary_Label'].map(sal_dict)

In [118]:
def manualEncoding(dataframe, col_name, *args):
    empty_dict = {}
    for idx, val in enumerate(args):
        empty_dict[val] = idx

    dataframe[f'{col_name}_id'] = dataframe[col_name].map(empty_dict)

In [119]:
# df[['Salary', 'Salary_Label', 'sal_id']]
manualEncoding(df, 'Salary_Label', 'Low Salary', 'Average Salary', 'High Salary')

In [120]:
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,DaysLateLast30,Absences,Hire_Year,Hire_Month,Hire_Day,Hire_Month_Name,Hire_Day_Name,Salary_Label,sal_id,Salary_Label_id
0,Bacong Alejandro,10250,0,2,1,1,3,3,0,50178,...,0,16,2015,1,5,January,Monday,Low Salary,0,0
1,Baczenski Rachael,10252,1,1,0,5,5,3,1,54670,...,0,12,2011,1,10,January,Monday,Low Salary,0,0
2,Barbara Thomas,10242,1,1,1,5,5,3,1,47211,...,0,15,2012,4,2,April,Monday,Low Salary,0,0
3,Barbossa Hector,10012,0,2,1,1,3,4,1,92328,...,0,9,2014,11,10,November,Monday,Average Salary,1,1
4,Barone Francesco A,10265,0,0,1,1,5,3,0,58709,...,0,7,2012,2,20,February,Monday,Low Salary,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,0,2,2011,7,11,July,Monday,Low Salary,0,0
307,Anderson Linda,10002,0,0,0,1,5,4,0,57568,...,0,15,2012,1,9,January,Monday,Low Salary,0,0
308,Andreola Colby,10194,0,0,0,1,4,3,0,95660,...,0,19,2014,11,10,November,Monday,Average Salary,1,1
309,Athwal Sam,10062,0,4,1,1,5,3,0,59365,...,0,19,2013,9,30,September,Monday,Low Salary,0,0
310,Bachiochi Linda,10114,0,0,0,3,5,3,1,47837,...,0,4,2009,7,6,July,Monday,Low Salary,0,0

## Split

In [121]:
# split(find, n=(index), expand=True/False(default))
df[['Sal_First', 'Sal_Last']] = df['Salary_Label'].str.split(' ', n=1, expand=True)

In [122]:
# df[['Last_Name', 'First_Name', 'Middle_Name']] = df['Employee_Name'].str.split(' ', n=2, expand=True)
# df = df.drop(columns = ['Last_Name', 'First_Name', 'Middle_Name'])

In [123]:
hr = pd.read_csv('Dataset/HR_Dataset Refresh.csv')
# hr.head()

In [124]:
hr = hr.drop_duplicates(subset='EmpID', keep='last')

In [125]:
last_first = hr['Employee_Name'].str.split(',', n=1, expand=True)
# last_first

In [126]:
first_middle = last_first[1].str.strip().str.split(' ', n=1, expand=True)
# first_middle

In [127]:
hr['First_Name'] = first_middle[0]
hr['Middle_Name'] = first_middle[1]
hr['Last_Name'] = last_first[0]

In [101]:
df.to_csv('data.csv', index=False)

In [129]:
df = df.merge(
    hr[['EmpID', 'First_Name', 'Middle_Name', 'Last_Name']],
    on = 'EmpID',
    how='left'
)

In [131]:
df = df.to_csv('cleaned_hr.csv', index=False)

In [100]:
df = df.drop(columns = ['First_Name_x', 'Middle_Name_x', 'Last_Name_x','First_Name_y', 'Middle_Name_y', 'Last_Name_y'])