In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('Dataset/financial_loan_data.xlsx')
df.head()

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
0,1077430,GA,INDIVIDUAL,< 1 year,Ryder,C,RENT,2021-02-11,2021-09-13,2021-04-13,...,C4,60 months,Source Verified,30000.0,0.0100,59.83,0.1527,2500,4,1009
1,1072053,CA,INDIVIDUAL,9 years,MKC Accounting,E,RENT,2021-01-01,2021-12-14,2021-01-15,...,E1,36 months,Source Verified,48000.0,0.0535,109.43,0.1864,3000,4,3939
2,1069243,CA,INDIVIDUAL,4 years,Chemat Technology Inc,C,RENT,2021-01-05,2021-12-12,2021-01-09,...,C5,36 months,Not Verified,50000.0,0.2088,421.65,0.1596,12000,11,3522
3,1041756,TX,INDIVIDUAL,< 1 year,barnes distribution,B,MORTGAGE,2021-02-25,2021-12-12,2021-03-12,...,B2,60 months,Source Verified,42000.0,0.0540,97.06,0.1065,4500,9,4911
4,1068350,IL,INDIVIDUAL,10+ years,J&J Steel Inc,A,MORTGAGE,2021-01-01,2021-12-14,2021-01-15,...,A1,36 months,Verified,83000.0,0.0231,106.53,0.0603,3500,28,3835

#### Data Cleaning

In [3]:
# df.isnull().sum()

In [4]:
# df.info()
df.columns

Index(['id', 'address_state', 'application_type', 'emp_length', 'emp_title',
       'grade', 'home_ownership', 'issue_date', 'last_credit_pull_date',
       'last_payment_date', 'loan_status', 'next_payment_date', 'member_id',
       'purpose', 'sub_grade', 'term', 'verification_status', 'annual_income',
       'dti', 'installment', 'int_rate', 'loan_amount', 'total_acc',
       'total_payment'],
      dtype='object')

In [5]:
## Fill employee title values
df.fillna({'emp_title': 'Unknown Title'}, inplace=True)

#### Feature Engineering

In [6]:
## Extract month data from loan issue date column
df['issue_month_num'] = df['issue_date'].dt.month
df['issue_month_name'] = df['issue_date'].dt.month_name()

In [7]:
# PMTD (Previous Month to Date)
previous_month = 11

# MTD (Month to Date)
current_month = 12

### KPIs

#### Total Loan Applications

In [13]:
Total_Loan_Applications = df['id'].count()
MTD_Total_Loan_Application = df[df['issue_month_num'] == current_month]['id'].count()
PMTD_Total_Loan_Application = df[df['issue_month_num'] == previous_month]['id'].count()
MoM_Total_Loan_Application = ((MTD_Total_Loan_Application - PMTD_Total_Loan_Application)/PMTD_Total_Loan_Application)*100

In [14]:
print(f'Total Loan Applications: {Total_Loan_Applications}')
print(f'MTD Total Loan Applications: {MTD_Total_Loan_Application}')
print(f'PMTD Total Loan Applications: {PMTD_Total_Loan_Application}')
print(f'MoM Total Loan Applications: {MoM_Total_Loan_Application:,.2f}%')

Total Loan Applications: 38576
MTD Total Loan Applications: 4314
PMTD Total Loan Applications: 4035
MoM Total Loan Applications: 6.91%

#### Total Funded Amount

In [15]:
Total_Funded_Amount = df['loan_amount'].sum()
MTD_Total_Funded_Amount = df[df['issue_month_num'] == current_month]['loan_amount'].sum()
PMTD_Total_Funded_Amount = df[df['issue_month_num'] == previous_month]['loan_amount'].sum()
MoM_Total_Funded_Amount = ((MTD_Total_Funded_Amount - PMTD_Total_Funded_Amount)/PMTD_Total_Funded_Amount)*100

In [16]:
print(f'Total Funded Amount: Rs.{Total_Funded_Amount:,.2f}')
print(f'MTD Total Funded Amount: Rs.{MTD_Total_Funded_Amount:,.2f}')
print(f'PMTD Total Funded Amount: Rs.{PMTD_Total_Funded_Amount:,.2f}')
print(f'MoM Total Funded Amount: {MoM_Total_Funded_Amount:,.2f}%')

Total Funded Amount: Rs.435,757,075.00
MTD Total Funded Amount: Rs.53,981,425.00
PMTD Total Funded Amount: Rs.47,754,825.00
MoM Total Funded Amount: 13.04%

#### Total Received Amount

In [17]:
Total_Received_Amount = df['total_payment'].sum()
MTD_Total_Received_Amount = df[df['issue_month_num'] == current_month]['total_payment'].sum()
PMTD_Total_Received_Amount = df[df['issue_month_num'] == previous_month]['total_payment'].sum()
MoM_Total_Received_Amount = ((MTD_Total_Received_Amount - PMTD_Total_Received_Amount)/PMTD_Total_Received_Amount)*100

In [18]:
print(f'Total Received Amount: Rs.{Total_Received_Amount:,.2f}')
print(f'MTD Total Received Amount: Rs.{MTD_Total_Received_Amount:,.2f}')
print(f'PMTD Total Received Amount: Rs.{PMTD_Total_Received_Amount:,.2f}')
print(f'MoM Total Received Amount: {MoM_Total_Received_Amount:,.2f}%')

Total Received Amount: Rs.473,070,933.00
MTD Total Received Amount: Rs.58,074,380.00
PMTD Total Received Amount: Rs.50,132,030.00
MoM Total Received Amount: 15.84%

#### Average Interest Rate

In [19]:
Average_Int_Rate = df['int_rate'].mean()*100
MTD_Average_Int_Rate = df[df['issue_month_num'] == current_month]['int_rate'].mean()*100
PMTD_Average_Int_Rate = df[df['issue_month_num'] == previous_month]['int_rate'].mean()*100
MoM_Average_Int_Rate = ((MTD_Average_Int_Rate - PMTD_Average_Int_Rate)/PMTD_Average_Int_Rate)*100

In [20]:
print(f'Average Interest Rate: {Average_Int_Rate:,.2f}%')
print(f'MTD Average Interest Rate: {MTD_Average_Int_Rate:,.2f}%')
print(f'PMTD Average Interest Rate: {PMTD_Average_Int_Rate:,.2f}%')
print(f'MoM Average Interest Rate: {MoM_Average_Int_Rate:,.2f}%')

Average Interest Rate: 12.05%
MTD Average Interest Rate: 12.36%
PMTD Average Interest Rate: 11.94%
MoM Average Interest Rate: 3.47%

#### Average Debt to Income Ratio

In [21]:
Average_Dti_Ratio = df['dti'].mean()*100
MTD_Average_Dti_Ratio = df[df['issue_month_num'] == current_month]['dti'].mean()*100
PMTD_Average_Dti_Ratio = df[df['issue_month_num'] == previous_month]['dti'].mean()*100
MoM_Average_Dti_Ratio = ((MTD_Average_Dti_Ratio - PMTD_Average_Dti_Ratio) / PMTD_Average_Dti_Ratio)*100

In [22]:
print(f'Average DTI Ratio: {Average_Dti_Ratio:,.2f}%')
print(f'MTD Average DTI Ratio: {MTD_Average_Dti_Ratio:,.2f}%')
print(f'PMTD Average DTI Ratio: {PMTD_Average_Dti_Ratio:,.2f}%')
print(f'MoM Average DTI Ratio: {MoM_Average_Dti_Ratio:,.2f}%')

Average DTI Ratio: 13.33%
MTD Average DTI Ratio: 13.67%
PMTD Average DTI Ratio: 13.30%
MoM Average DTI Ratio: 2.73%

## Good Loan vs. Bad Loan

In [23]:
## Extract good loan and bad loan data
good_loan = df[df['loan_status'].isin(['Current', 'Fully Paid'])]
bad_loan = df[df['loan_status'] == 'Charged Off']

### Good Loan KPIs

In [24]:
Good_Loan_Applications = good_loan['id'].count()
Good_Loan_Application_Pct = (Good_Loan_Applications / Total_Loan_Applications)*100
Good_Loan_Funded_Amount = good_loan['loan_amount'].sum()
Good_Loan_Received_Amount = good_loan['total_payment'].sum()

In [25]:
print(f'Good Loan Applications: {Good_Loan_Applications}')
print(f'Good Loan Application Pct: {Good_Loan_Application_Pct:,.2f}%')
print(f'Good Loan Funded Amount: Rs.{Good_Loan_Funded_Amount:,.2f}')
print(f'Good Loan Received Amount: Rs.{Good_Loan_Received_Amount:,.2f}')

Good Loan Applications: 33243
Good Loan Application Pct: 86.18%
Good Loan Funded Amount: Rs.370,224,850.00
Good Loan Received Amount: Rs.435,786,170.00

### Bad Loan KPIs

In [26]:
Bad_Loan_Applications = bad_loan['id'].count()
Bad_Loan_Application_Pct = (Bad_Loan_Applications / Total_Loan_Applications)*100
Bad_Loan_Funded_Amount = bad_loan['loan_amount'].sum()
Bad_Loan_Received_Amount = bad_loan['total_payment'].sum()

In [27]:
print(f'Bad Loan Applications: {Bad_Loan_Applications}')
print(f'Bad Loan Application Pct: {Bad_Loan_Application_Pct:,.2f}%')
print(f'Bad Loan Funded Amount: Rs.{Bad_Loan_Funded_Amount:,.2f}')
print(f'Bad Loan Received Amount: Rs.{Bad_Loan_Received_Amount:,.2f}')

Bad Loan Applications: 5333
Bad Loan Application Pct: 13.82%
Bad Loan Funded Amount: Rs.65,532,225.00
Bad Loan Received Amount: Rs.37,284,763.00

### Loan Status Grid View

In [28]:
current_df = df[df['issue_month_num'] == current_month]
MTD_FA = current_df.groupby('loan_status')['loan_amount'].sum().reset_index()
MTD_RA = current_df.groupby('loan_status')['total_payment'].sum().reset_index()

In [43]:
# Currency Converter
def currencyConverter(dataframe, prefix, *args):
    for col in args:
        dataframe[col] = dataframe[col].map(f'{prefix}''{:,.2f}'.format)
        
# Percentage Converter
def pctConverter(dataframe, suffix, *args):
    for col in args:
        dataframe[col] = (dataframe[col]*100).map('{:,.2f}'f'{suffix}'.format)

In [45]:
loan_grid = df.groupby('loan_status').agg(
    Total_Loan_Applications = ('id', 'count'),
    Total_Funded_Amount = ('loan_amount', 'sum'),
    Total_Received_Amount = ('total_payment', 'sum'),
    Average_Int_Rate = ('int_rate', 'mean'),
    Average_Dti_Ratio = ('dti', 'mean')
).reset_index()

loan_grid['MTD_Funded_Amount'] = MTD_FA['loan_amount']
loan_grid['MTD_Received_Amount'] = MTD_RA['total_payment']

currencyConverter(loan_grid, 'Rs.', 'Total_Funded_Amount', 'Total_Received_Amount',
                 'MTD_Funded_Amount', 'MTD_Received_Amount')

pctConverter(loan_grid, '%', 'Average_Int_Rate', 'Average_Dti_Ratio')

loan_grid.columns = loan_grid.columns.str.replace('_', ' ', regex=False) 

loan_grid

,loan status,Total Loan Applications,Total Funded Amount,Total Received Amount,Average Int Rate,Average Dti Ratio,MTD Funded Amount,MTD Received Amount
0,Charged Off,5333,"Rs.65,532,225.00","Rs.37,284,763.00",13.88%,14.00%,"Rs.8,732,775.00","Rs.5,324,211.00"
1,Current,1098,"Rs.18,866,500.00","Rs.24,199,914.00",15.10%,14.72%,"Rs.3,946,625.00","Rs.4,934,318.00"
2,Fully Paid,32145,"Rs.351,358,350.00","Rs.411,586,256.00",11.64%,13.17%,"Rs.41,302,025.00","Rs.47,815,851.00"

## Analysis

### Monthly Trend

In [52]:
monthly_trend = df.groupby(['issue_month_num', 'issue_month_name']).agg(
    Total_Loan_Application = ('id', 'count'),
    Total_Funded_Amount = ('loan_amount', 'sum'),
    Total_Received_Amount = ('total_payment', 'sum')
).reset_index().rename(
    columns = {'issue_month_name': 'Month Name'}
)[['Month Name', 'Total_Loan_Application', 'Total_Funded_Amount', 'Total_Received_Amount']]

currencyConverter(monthly_trend, 'Rs.', 'Total_Funded_Amount', 'Total_Received_Amount')

monthly_trend.columns = monthly_trend.columns.str.replace('_', ' ', regex=False)

monthly_trend

,Month Name,Total Loan Application,Total Funded Amount,Total Received Amount
0,January,2332,"Rs.25,031,650.00","Rs.27,578,836.00"
1,February,2279,"Rs.24,647,825.00","Rs.27,717,745.00"
2,March,2627,"Rs.28,875,700.00","Rs.32,264,400.00"
3,April,2755,"Rs.29,800,800.00","Rs.32,495,533.00"
4,May,2911,"Rs.31,738,350.00","Rs.33,750,523.00"
5,June,3184,"Rs.34,161,475.00","Rs.36,164,533.00"
6,July,3366,"Rs.35,813,900.00","Rs.38,827,220.00"
7,August,3441,"Rs.38,149,600.00","Rs.42,682,218.00"
8,September,3536,"Rs.40,907,725.00","Rs.43,983,948.00"
9,October,3796,"Rs.44,893,800.00","Rs.49,399,567.00"
10,November,4035,"Rs.47,754,825.00","Rs.50,132,030.00"
11,December,4314,"Rs.53,981,425.00","Rs.58,074,380.00"

### Regional Analysis

In [56]:
region_analysis = df.groupby('address_state').agg(
    Total_Loan_Application = ('id', 'count'),
    Total_Funded_Amount = ('loan_amount', 'sum'),
    Total_Received_Amount = ('total_payment', 'sum')
).reset_index().rename(
    columns = {'address_state': 'Region'}
)[['Region', 'Total_Loan_Application', 'Total_Funded_Amount', 'Total_Received_Amount']]

currencyConverter(region_analysis, 'Rs.', 'Total_Funded_Amount', 'Total_Received_Amount')

region_analysis.columns = region_analysis.columns.str.replace('_', ' ', regex=False)

region_analysis

   Region  Total Loan Application Total Funded Amount Total Received Amount
0      AK                      78     Rs.1,031,800.00       Rs.1,108,570.00
1      AL                     432     Rs.4,949,225.00       Rs.5,492,272.00
2      AR                     236     Rs.2,529,700.00       Rs.2,777,875.00
3      AZ                     833     Rs.9,206,000.00      Rs.10,041,986.00
4      CA                    6894    Rs.78,484,125.00      Rs.83,901,234.00
5      CO                     770     Rs.8,976,000.00       Rs.9,845,810.00
6      CT                     730     Rs.8,435,575.00       Rs.9,357,612.00
7      DC                     214     Rs.2,652,350.00       Rs.2,921,854.00
8      DE                     110     Rs.1,138,100.00       Rs.1,269,136.00
9      FL                    2773    Rs.30,046,125.00      Rs.31,601,905.00
10     GA                    1355    Rs.15,480,325.00      Rs.16,728,040.00
11     HI                     170     Rs.1,850,525.00       Rs.2,080,184.00
12     IA                       5        Rs.56,450.00          Rs.64,482.00
13     ID                       6        Rs.59,750.00          Rs.65,329.00
14     IL                    1486    Rs.17,124,225.00      Rs.18,875,941.00
15     IN                       9        Rs.86,225.00          Rs.85,521.00
16     KS                     260     Rs.2,872,325.00       Rs.3,247,394.00
17     KY                     320     Rs.3,504,100.00       Rs.3,792,530.00
18     LA                     426     Rs.4,498,900.00       Rs.5,001,160.00
19     MA                    1310    Rs.15,051,000.00      Rs.16,676,279.00
20     MD                    1027    Rs.11,911,400.00      Rs.12,985,170.00
21     ME                       3         Rs.9,200.00          Rs.10,808.00
22     MI                     685     Rs.7,829,900.00       Rs.8,543,660.00
23     MN                     592     Rs.6,302,600.00       Rs.6,750,746.00
24     MO                     660     Rs.7,151,175.00       Rs.7,692,732.00
25     MS                      19       Rs.139,125.00         Rs.149,342.00
26     MT                      79       Rs.829,525.00         Rs.892,047.00
27     NC                     759     Rs.8,787,575.00       Rs.9,534,813.00
28     NE                       5        Rs.31,700.00          Rs.24,542.00
29     NH                     161     Rs.1,917,900.00       Rs.2,101,386.00
30     NJ                    1822    Rs.21,657,475.00      Rs.23,425,159.00
31     NM                     183     Rs.1,916,775.00       Rs.2,084,485.00
32     NV                     482     Rs.5,307,375.00       Rs.5,451,443.00
33     NY                    3701    Rs.42,077,050.00      Rs.46,108,181.00
34     OH                    1188    Rs.12,991,375.00      Rs.14,330,148.00
35     OK                     293     Rs.3,365,725.00       Rs.3,712,649.00
36     OR                     436     Rs.4,720,150.00       Rs.4,966,903.00
37     PA                    1482    Rs.15,826,525.00      Rs.17,462,908.00
38     RI                     196     Rs.1,883,025.00       Rs.2,001,774.00
39     SC                     464     Rs.5,080,475.00       Rs.5,462,458.00
40     SD                      63       Rs.606,150.00         Rs.656,514.00
41     TN                      17       Rs.162,175.00         Rs.141,522.00
42     TX                    2664    Rs.31,236,650.00      Rs.34,392,715.00
43     UT                     252     Rs.2,849,225.00       Rs.2,952,412.00
44     VA                    1375    Rs.15,982,650.00      Rs.17,711,443.00
45     VT                      54       Rs.504,100.00         Rs.534,973.00
46     WA                     805     Rs.8,855,525.00       Rs.9,531,739.00
47     WI                     446     Rs.5,070,450.00       Rs.5,485,161.00
48     WV                     167     Rs.1,830,525.00       Rs.1,991,936.00
49     WY                      79       Rs.890,750.00       Rs.1,046,050.00

### Loan Term Analysis

In [58]:
loan_term = df.groupby('term').agg(
    Total_Loan_Application = ('id', 'count'),
    Total_Funded_Amount = ('loan_amount', 'sum'),
    Total_Received_Amount = ('total_payment', 'sum')
).reset_index().rename(
    columns = {'term': 'Loan Term'}
)[['Loan Term', 'Total_Loan_Application', 'Total_Funded_Amount', 'Total_Received_Amount']]

currencyConverter(loan_term, 'Rs.', 'Total_Funded_Amount', 'Total_Received_Amount')

loan_term.columns = loan_term.columns.str.replace('_', ' ', regex=False)
loan_term

,Loan Term,Total Loan Application,Total Funded Amount,Total Received Amount
0,36 months,28237,"Rs.273,041,225.00","Rs.294,709,458.00"
1,60 months,10339,"Rs.162,715,850.00","Rs.178,361,475.00"

### Employee Length Analysis

In [60]:
employee_len_analysis = df.groupby('emp_length').agg(
    Total_Loan_Application = ('id', 'count'),
    Total_Funded_Amount = ('loan_amount', 'sum'),
    Total_Received_Amount = ('total_payment', 'sum')
).reset_index().rename(
    columns = {'emp_length': 'Employee Length'}
)[['Employee Length', 'Total_Loan_Application', 'Total_Funded_Amount', 'Total_Received_Amount']]

currencyConverter(employee_len_analysis, 'Rs.', 'Total_Funded_Amount', 'Total_Received_Amount')

employee_len_analysis.columns = employee_len_analysis.columns.str.replace('_', ' ', regex=False)

employee_len_analysis

,Employee Length,Total Loan Application,Total Funded Amount,Total Received Amount
0,1 year,3229,"Rs.32,883,125.00","Rs.35,498,348.00"
1,10+ years,8870,"Rs.116,115,950.00","Rs.125,871,616.00"
2,2 years,4382,"Rs.44,967,975.00","Rs.49,206,961.00"
3,3 years,4088,"Rs.43,937,850.00","Rs.47,551,832.00"
4,4 years,3428,"Rs.37,600,375.00","Rs.40,964,850.00"
5,5 years,3273,"Rs.36,973,625.00","Rs.40,397,571.00"
6,6 years,2228,"Rs.25,612,650.00","Rs.27,908,658.00"
7,7 years,1772,"Rs.20,811,725.00","Rs.22,584,136.00"
8,8 years,1476,"Rs.17,558,950.00","Rs.19,025,777.00"
9,9 years,1255,"Rs.15,084,225.00","Rs.16,516,173.00"
10,< 1 year,4575,"Rs.44,210,625.00","Rs.47,545,011.00"

### Loan Purpose Analysis

In [66]:
loan_purpose = df.groupby('purpose').agg(
    Total_Loan_Application = ('id', 'count'),
    Total_Funded_Amount = ('loan_amount', 'sum'),
    Total_Received_Amount = ('total_payment', 'sum')
).reset_index().rename(
    columns = {'purpose': 'Loan Purpose'}
).sort_values(ascending=False, by='Total_Loan_Application', ignore_index=True)[
    ['Loan Purpose', 'Total_Loan_Application', 'Total_Funded_Amount', 'Total_Received_Amount']
]

currencyConverter(loan_purpose, 'Rs.', 'Total_Funded_Amount', 'Total_Received_Amount')

loan_purpose.columns = loan_purpose.columns.str.replace('_', ' ', regex=False)

loan_purpose

,Loan Purpose,Total Loan Application,Total Funded Amount,Total Received Amount
0,Debt consolidation,18214,"Rs.232,459,675.00","Rs.253,801,871.00"
1,credit card,4998,"Rs.58,885,175.00","Rs.65,214,084.00"
2,other,3824,"Rs.31,155,750.00","Rs.33,289,676.00"
3,home improvement,2876,"Rs.33,350,775.00","Rs.36,380,930.00"
4,major purchase,2110,"Rs.17,251,600.00","Rs.18,676,927.00"
5,small business,1776,"Rs.24,123,100.00","Rs.23,814,817.00"
6,car,1497,"Rs.10,223,575.00","Rs.11,324,914.00"
7,wedding,928,"Rs.9,225,800.00","Rs.10,266,856.00"
8,medical,667,"Rs.5,533,225.00","Rs.5,851,372.00"
9,moving,559,"Rs.3,748,125.00","Rs.3,999,899.00"
10,house,366,"Rs.4,824,925.00","Rs.5,185,538.00"
11,vacation,352,"Rs.1,967,950.00","Rs.2,116,738.00"
12,educational,315,"Rs.2,161,650.00","Rs.2,248,380.00"
13,renewable_energy,94,"Rs.845,750.00","Rs.898,931.00"

### Home Ownership Analysis

In [68]:
home_ownership = df.groupby('home_ownership').agg(
    Total_Loan_Application = ('id', 'count'),
    Total_Funded_Amount = ('loan_amount', 'sum'),
    Total_Received_Amount = ('total_payment', 'sum')
).reset_index().rename(
    columns = {'home_ownership': 'Home Ownership'}
).sort_values(ascending=False, by='Total_Loan_Application', ignore_index=True)[
    ['Home Ownership', 'Total_Loan_Application', 'Total_Funded_Amount', 'Total_Received_Amount']
]

currencyConverter(home_ownership, 'Rs.', 'Total_Funded_Amount', 'Total_Received_Amount')

home_ownership.columns = home_ownership.columns.str.replace('_', ' ', regex=False)

home_ownership

,Home Ownership,Total Loan Application,Total Funded Amount,Total Received Amount
0,RENT,18439,"Rs.185,768,475.00","Rs.201,823,056.00"
1,MORTGAGE,17198,"Rs.219,329,150.00","Rs.238,474,438.00"
2,OWN,2838,"Rs.29,597,675.00","Rs.31,729,129.00"
3,OTHER,98,"Rs.1,044,975.00","Rs.1,025,257.00"
4,NONE,3,"Rs.16,800.00","Rs.19,053.00"