In [ ]:
'''
Use of Pandas
----------------
- Conditional Filtering (Data Filtering)
- Data Wrangling
    - Data Cleaning
    - Feature Engineering
    - Data Analysis
    - Files Read/Write and Input/Ouput
'''

In [1]:
import pandas as pd

In [6]:
# 1D -> Series
# 2D -> DataFrame

numbers = pd.Series([1, 2, 3, 4, 5, 6, 7], index=['A', 'B', 'C', 'D', 'E', 'F', 'G'])
numbers

A    1
B    2
C    3
D    4
E    5
F    6
G    7
dtype: int64

In [5]:
product_details = pd.DataFrame([
    ['Mobile', 'Samsung', 2, 50000],
    ['Charger', 'Anker', 5, 3000],
    ['TV', 'MI', 1, 75000],
    ['Bag', 'Bello', 3, 4500]
], columns=['Product Name', 'Product Brand', 'Quantity', 'Price'],
    index = ['A', 'B', 'C', 'D'])
product_details

  Product Name Product Brand  Quantity  Price
A       Mobile       Samsung         2  50000
B      Charger         Anker         5   3000
C           TV            MI         1  75000
D          Bag         Bello         3   4500

In [7]:
product_details.shape

(4, 4)

In [8]:
product_details.size

16

In [9]:
product_details.ndim

2

In [10]:
numbers.ndim

1

## Slicing

In [15]:
numbers[1:7]

B    2
C    3
D    4
E    5
F    6
G    7
dtype: int64

In [16]:
numbers['B':'G']

B    2
C    3
D    4
E    5
F    6
G    7
dtype: int64

## Loc and ILoc

In [ ]:
'''
- Loc -> Location -> Use alphabetical index
- ILoc -> Integer Location -> Use numeric index
'''

In [22]:
product_details.iloc[1:3, 1:3]

  Product Brand  Quantity
B         Anker         5
C            MI         1

In [23]:
product_details.loc['B':'C', 'Product Brand':'Quantity']

  Product Brand  Quantity
B         Anker         5
C            MI         1

In [24]:
product_details.iloc[
    [1, 3], # row
    [0, 2] # column
]

  Product Name  Quantity
B      Charger         5
D          Bag         3

In [26]:
product_details.loc[
    ['A', 'D'],
    ['Product Name', 'Quantity', 'Price']
]

  Product Name  Quantity  Price
A       Mobile         2  50000
D          Bag         3   4500

In [27]:
# To check information of data
product_details.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, A to D
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Product Name   4 non-null      object
 1   Product Brand  4 non-null      object
 2   Quantity       4 non-null      int64
 3   Price          4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 332.0+ bytes

In [ ]:
'''
Read Files
--------------
- read_csv(file_path)
- read_excel(file_path)
- read_json(file_path)
- read_sql(file_path)

Null Values
-----------
- NaN -> Not a Number -> String, Number
- NaT -> Not a Time -> Date, Time
'''

In [28]:
df = pd.read_csv('Dataset/Employees.csv')
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,6/17/2003,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,9/21/2005,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,1/13/2001,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,1/3/2006,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,5/21/2007,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,6/7/2002,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,6/7/2002,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,6/7/2002,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,6/7/2002,AC_ACCOUNT,8300,NaN,205.0,110.0

In [ ]:
'''
    # What are the data types in dataframe?
        -> Int, Str, Float, Boolean, Complex, None, DateTime
        
    # What are the types of data in dataframe?
        - Numeric
            a. Discrete
                -> Whole Numbers
                -> Id Columns
            b. Continuous
                -> Whole Numbers / Decimal Numbers
                -> Salary, Grades
                
        - Categorical
            a. Nominal
                -> Category which cannot be compared.
                -> Colors, Gender, Caste, Blood Group
                
            b. Ordinal
                -> Category which can be compared.
                -> High/Low/Medium
'''