In [ ]:
'''
    ERD (Entity Relationship Diagram)
    ------------------------------------
    1. Constraints
        a. Primary Key
        b. Foreign Key
        c. Unique
        d. Check
        e. Null / default
        f. Not Null

    - Constraints -> Data Integrity
    - Data Integrity is Data Security but Data Security is not Data Integrity?
        
    2. Keys
        a. Primary Key
        b. Foreign Key
        c. Composite Key
        d. Alternate Key
        e. Surrogate Key
        f. Candidate Key
        g. Participatory Key / Super Key

    3. Relationship
        a. One to One
        b. One to Many
        c. Many to One
        d. Many to Many

    4. Foreign Key
        - foreign key (staff_id) references staff (staff_id)
        a. Types of Foreign Key
            i. Cascade
            ii. No Action
            iii. Set Null
            iv. Set Default

Types of RDBMS
---------------
1. MySQL
2. Posgres SQL
3. MSSQL Server
4. Oracle
'''

In [ ]:
'''
Topics
-------------
1. Basic SQL Query
2. Group By and Having
3. SQL Joins
    i. Inner Join
    ii. Left Join
    iii. Right Join
    iv. Outer Join
    v. Self Join
    vi. Natural Join
    vii. Cross Join
4. Sub Queries
    i. Single Row Subquery
    ii. Multi Row Subquery
    iii. Correlated Subquery
5. CTE (Common Table Expressions)
6. Window Functions
    - Row_Number(), Rank(), Dense_Rank(), NTile(), Lead(), Lag(), Running Sum, Moving Average
7. Advanced SQL
    - Indexing
    - Synonyms
    - Views
    - Basic Stored Procedure (Application Level Queries)
8. Python and SQL Connection using SQL Alchemy


Install SSMS   Close    Connect Now (1)

Connect Now (1) -> CMD -> 1 row affected.. -> Close CMD

'''

In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
server = 'RUSAN'
database = 'BikeStores'

connection_url = f"mssql+pyodbc://@{server}/{database}?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
engine = create_engine(connection_url)

In [3]:
query = '''
    select
    	CONCAT(sc.first_name, ' ', sc.last_name) as customer_name,
    	COUNT(soi.product_id) as total_products,
    	sum((soi.list_price * soi.quantity) * (1 - soi.discount)) as total_spent
    from sales.customers sc
    join sales.orders so
    on sc.customer_id = so.customer_id
    join sales.order_items soi
    on so.order_id = soi.order_id
    group by CONCAT(sc.first_name, ' ', sc.last_name);
'''
query_df = pd.read_sql(query, engine)
query_df

        customer_name  total_products  total_spent
0         Aaron Knapp               2    5927.5510
1          Abbey Pugh               2    4132.9920
2         Abby Gamble               7   32803.0062
3      Abram Copeland               5   24607.0261
4      Adam Henderson               3    3695.4745
...               ...             ...          ...
1439     Zona Cameron               1    2696.9907
1440        Zora Ford               4    7663.9490
1441   Zoraida Patton               4    7004.8410
1442  Zulema Browning               2    1265.9724
1443   Zulema Clemons               1     512.9810

[1444 rows x 3 columns]

In [4]:
query_sp = '''
    Declare @output_message varchar(100)

    exec usp_findOrderStatus @order_id=1481, @Response_Message = @output_message output;
    
    select @output_message as message;
'''
query_sp_df = pd.read_sql(query_sp, engine)
query_sp_df

                        message
0  Order Id 1481 is in pending.